FROM nginx:latest
LABEL maintainer "Matheus <matheusrf96@gmail.com>"

RUN echo '<h1>Sem conteúdo</h1><br /><a href="index.html">Voltar</a>' > /usr/share/nginx/html/conteudo.html
COPY *.html /usr/share/nginx/html/